version: '3'
services:
  topo-planner:
    container_name: topo-planner
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /var/log/topo-planner:/var/log/topo-planner
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 